### ISSUE TITLE
Forms example not working in IOS

### ISSUE THREAD

**Issue by PaulVrugt** [martijn00/XamarinMediaManager#256]
Hello,

I'm trying to see if i can use this component in my app. However, in IOS the forms example is not working. No video is displayed, and no error is shown. I first tried to implement it in my own app, later downloaded the example from github, but this is also not working. Am I doing something wrong?

**Comment by aiviet** [comment]
In Info.plist, make sure your have this permission enabled:
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>

**Comment by jimespen** [comment]
@aiviet I also tried doing this for my Xamarin.iOS app, but I'm experiencing the exact same behaviour.

**Comment by danielwebstep** [comment]
@jimespen : Have you tried using https instead of http for the video url?

**Comment by jimespen** [comment]
@danielwebstep Yes, I've tried that, but the results are the same. I've also tried to play local files from the device, but it's no different from what BillFulton is experiencing at https://github.com/martijn00/XamarinMediaManager/issues/190.

The console spits out this for both local and web videos (timestamps removed for simplicity):
```
Observer triggered for loadedTimeRanges
Observer triggered for status
Status Observed Method Unknown
-[AVAsset loadValuesAsynchronouslyForKeys:completionHandler:] invoked with unrecognized keys (
    title,
    artwork,
    artist
).
Observer triggered for status
Status Observed Method ReadyToPlay
Observer triggered for status
Status Observed Method ReadyToPlay
```
and I don't really know what to take from this. I would assume the unrecognized keys for the completion handler doesn't prevent the video from being shown, but I could of course be wrong.

**Comment by danielwebstep** [comment]
@jimespen : have you remembered to initialize the component in the appdelegate? (you need to include the Plugin.MediaManager.Forms component)

`public override bool FinishedLaunching(UIApplication app, NSDictionary options)
{
VideoViewRenderer.Init();
}`

**Comment by marualderete** [comment]
I have the same behavior, did you find how to resolve it?

**Comment by PaulVrugt** [comment]
Nope, I moved to a different component

**Comment by marualderete** [comment]
:( ouch. Thanks for response
could you tell which component did you find, if you don't mind to mention it of course?

**Comment by PaulVrugt** [comment]
@marualderete 
Eventually I went with https://github.com/inthehand/InTheHand.Forms
It has a media player the does what I want it to do, after I fixed some bugs in it.

**Comment by joechihe** [comment]
I tried this component today, and it still failing for me with the same behavior described here.
I'm using version 0.5.5.
Running on iOS 12.2

**Comment by ihassantariq** [comment]
@martijn00 @joechihe I am having the same issue. Have you able to find any solution?

**Comment by martijn00** [comment]
@ihassantariq please open a new issue.

**Comment by ihassantariq** [comment]
@martijn00 Okay. Let me do that.
