### ISSUE TITLE
[Android] App crash because MediaSession is null after exit and reopen app

### ISSUE THREAD

**Issue by rrispoli** [martijn00/XamarinMediaManager#487]
## 🐛 Bug Report

For some reason, if you press the back button to exit the app, it stop the current media and remove the notification. When the app is reopened the MediaSession is always null and because of this the plugin doesn't play any media and SetPlayerView not work too.

### Expected behavior
The media continue to play and MediaSession still available.
Note: if you press the middle Android button (Home) to exit the app, the media still playing and notification remain in the screen. The problem is only with back button.

### Reproduction steps
1) Run the ElementPlayer.Android sample.
2) Play Google Glass (MP4,H264) video.
3) Press back button to close the app (notice that the notification disappear too).
4) Reopen the app.
5) Try to play same or other video and the app crash.

### Configuration

**Version:** 0.6.1 and 0.6.2 (with ExoPlayer 2.8.8)

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
For some reason the service dies when closing the app with the backbutton. I'm not sure why yet, and some comments on ExoPlayer suggest that this is fixed in a later version than 2.8.8.

It would be helpful if you could help look into this issue together.

**Comment by rrispoli** [comment]
I'm trying to understand what is the main problem that cause the service die.
Do you have plans to update the plugin to work with ExoPlayer 2.9.6? I tried to update in my project just to test, but it crash with System.MissingMethodException: Method not found: void Com.Google.Android.Exoplayer2.Source.ConcatenatingMediaSource..ctor()

**Comment by martijn00** [comment]
@rrispoli i'm holding off on updating for now because we need Java 1.8 to run. This is only possible with VS2019 with d8 and r8 enabled. There is a branch where i did the update: https://github.com/martijn00/XamarinMediaManager/tree/exoplayer-update

I hope Xamarin gets d8/r8 stable enough sometime soon to be able to update.

Why i don't get why it dies is because of this line: https://github.com/martijn00/XamarinMediaManager/blob/develop/MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs#L75

It should make the service go in the foreground and not die, but for some reason it is not.

**Comment by rrispoli** [comment]
Thanks, I already make the updates in my system and project to work with d8 and r8. I'll make some tests with the master and update branch plugin repository.

**Comment by martijn00** [comment]
Let me know how it goes. I'm very interested in it! I'll also update exoplayer to the latest sometime soon.

**Comment by martijn00** [comment]
@rrispoli my branch has a working version with exoplayer 2.9.6 now. The service still dies in there.

**Comment by rrispoli** [comment]
@martijn00 I made some tests with the exoplayer-update branch with Exoplayer 2.9.6. I found this, please check if it help:

I Run the app, play video, press back button, reopen the app, play some video, and see that the crash is here: https://github.com/martijn00/XamarinMediaManager/blob/exoplayer-update/MediaManager/Platforms/Android/Player/AndroidMediaPlayer.cs#L113

The MediaSession is null because the back button is calling the OnDestroy method of MediaBrowserService and it release the MediaSession here: https://github.com/martijn00/XamarinMediaManager/blob/exoplayer-update/MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs#L133

The ExoPlayer is also released in MediaBrowserService OnDestroy here: https://github.com/martijn00/XamarinMediaManager/blob/exoplayer-update/MediaManager/Platforms/Android/MediaSession/MediaBrowserService.cs#L130

I tested again to see what happen when I press the middle button (home) and the MediaBrowserService OnDestroy was not called.

I comment the lines that Release, Dispose and set to null the MediaPlayer and MediaSession to check and the video still running, the notification still visible and when I reopen the app, I can play a new video without crash.

So, I think that the real problem is not in ExoPlayer, but in this MediaBrowserService that for some reason is being killed and calling OnDestroy on back button press.

**Comment by martijn00** [comment]
This should be fixed in 0.6.4. Let me know how it goes.

**Comment by SatyaRamprasad** [comment]
@martijn00 i am still getting the same exception in 0.6.7

**Comment by Pujolsluis** [comment]
Hey @martijn00 , I'm seeing this error in 8.17 aswell, I enabled d8 and r8 but it still continues🤔 I'm looking into it as well to see what could be the problem

**Comment by rustem08** [comment]
I have same issue in 0.9.6. 
I have page with video player. I don't create this page for android platform, but this issue is occured.

**Comment by DamienDoumer** [comment]
Anything new please  ?
