### ISSUE TITLE
PlayQueueItem does not work

### ISSUE THREAD

**Issue by pinewoodranger** [martijn00/XamarinMediaManager#613]
## 🐛 Bug Report

```
list.ForEach(item => CrossMediaManager.Current.Queue.Add(item));
await CrossMediaManager.Current.PlayQueueItem(2);
```
Nothing happens. If I replace '2' with a concrete IMediaItem that IS in the collection, nothing happens.

**Version:** 0.8.9

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
This is indeed a bug. It works when passing a list to Play initially, but not when manually adding items to the queue.

**Comment by BuddyLReno** [comment]
Really interested to see when this one gets fixed. Actively working on an audio app that is essentially manipulating a large queue.

**Comment by BuddyLReno** [comment]
Don't know if this is exactly related but we started to try to manage our own list of media items and just pass new versions of that queue to `CrossMediaManager.Current.Play`.  This works in that it'll play the items in the queue, but the second time and on that a new queue is assigned, the code no longer fires the `MediaItemFinished` event.

**Comment by martijn00** [comment]
Should be fixed in 0.8.10. Let me know if everything works.

**Comment by MasKhan20** [comment]
await CrossMediaManager.Current.PlayQueueItem(CrossMediaManager.Current.Queue.Current);
Still not working with version 0.8.11 on Android.

I add the `MediaItem`'s like this:

    CrossMediaManager.Current.Queue.Add(await CrossMediaManager.Current.Extractor.CreateMediaItem(new FileInfo(surah.File)));

`CrossMediaManager.Current.Play(CrossMediaManager.Current.Queue.Current);` works but there is no queue

I though this issue was fixed :(

**Comment by BuddyLReno** [comment]
@MasKhan20 Have you tried just passing an integer to see if the queue plays? I would also create your new media item on a separate line so you can breakpoint there and investigate that your media item is being created as you intend it to.  I haven't had time to try the new version yet myself but I would start with a simple hardcoded test first.

**Comment by MasKhan20** [comment]
Yes already tried using an integer. With `Play()` a notification is created with playback controls but not with `PlayQueueItem()`. Further proof that this method has a bug.

**Comment by viethungluu** [comment]
Hi all,

Im facing the same issue with v1.0.4. Did you found the way to solve this issue?
